AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  survey-backend

  Sample SAM Template for survey-backend
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SurveysTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: surveys-table
      AttributeDefinitions: 
        - AttributeName: admin_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: admin_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DynamoDBTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref SurveysTable
